### ISSUE TITLE
Filter out unwanted file types

### ISSUE THREAD

**Issue by TBRC-JimK** [BuddhistDigitalResourceCenter/drs-deposit#14]
When batch builder sees non-image file types in Paged Object content. it fails the batch.
[DbinBatchError.txt](https://github.com/BuddhistDigitalResourceCenter/drs-deposit/files/1572672/DbinBatchError.txt)

At last count, these were
*.db
*.DS_Store
jsk: 1/3/2018: add .pdf

**Comment by jeffwallman** [comment]
What about multi-page tiffs?

**Comment by xristy** [comment]
there's no simple filter based on file extension to exclude multi-page tiffs. Unless there is a very very cheap command to detect then it will be cheaper to let BB detect the apparently few occurrences that can then be collected into a list for batch correct per the discussion in [#15](https://github.com/BuddhistDigitalResourceCenter/drs-deposit/issues/15#issuecomment-352907915).

As mentioned there, it might be a false report from jhove fits so this could be investigated.

In the meantime Jim will be filtering / removing in the local copy the Thumbs.db and ever present .DS_Store chaff.

There is [a separate library-issue](https://github.com/BuddhistDigitalResourceCenter/library-issues/issues/115) to deal with purging the archive copies of *.db and .DS_Store

**Comment by TBRC-Travis** [comment]
_>> there's no simple filter based on file extension to exclude multi-page tiffs. Unless there is a very very cheap command to detect..._

Indeed there is not one that I know of.  as Chris mentioned it will be easiest to just detect these during batch building and dealt with on a case-by-case basis.

**Comment by TBRC-JimK** [comment]
There are free tiff utilities, but they're open source brew packages, AFAIK.

**Comment by TBRC-JimK** [comment]
There are free tiff utilities, but they're open source brew packages, AFAIK.

**Comment by xristy** [comment]
@TBRC-JimK feel free to open issues in library-issues as you see fit.

As for the detection of multi-page tiffs, both Travis and I are saying that it isn't practical to run an extra command line utility to detect the _apparently_ very few instances in the archive. The BB processing is effective at finding them and since it will only take a few days to run on all the available Works we'll have a list of suspects in relatively short order.

Further, it might be worth testing whether the jhove fits report is correct that the tiffs in question actually are multi-page.

**Comment by TBRC-JimK** [comment]
Closed by adding PDF. Last known banned file type Commit [864838b](https://github.com/BuddhistDigitalResourceCenter/drs-deposit/commit/864838b9075914e5769787a2635f7c0c9d5173c0)
